In [12]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Y.Nikithasri\Downloads\student.csv")
#print(df.head())
name = df.groupby('name')
print(name.first()) 
#print(df.columns)

             id  class  mark  gender
name
Alex John     6   Four    55    male
Arnold        3  Three    55    male
Asruid        8   Five    85    male
Big John     10   Four    55  female
John Deo      1   Four    75  female
John Mike     5   Four    60  female
Krish Star    4   Four    60  female
Max Ruin      2  Three    85    male
My John Rob   7  Fifth    78    male
Tes Qry       9    Six    78    male

In [16]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Y.Nikithasri\Downloads\student.csv")
grouping = df.groupby(['name', 'gender'])
print(grouping.first())

                    id  class  mark
name        gender
Alex John   male     6   Four    55
Arnold      male     3  Three    55
Asruid      male     8   Five    85
Big John    female  10   Four    55
John Deo    female   1   Four    75
John Mike   female   5   Four    60
Krish Star  female   4   Four    60
Max Ruin    male     2  Three    85
My John Rob male     7  Fifth    78
Tes Qry     male     9    Six    78

In [18]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Y.Nikithasri\Downloads\student.csv")
aggregated_data = df.groupby(['name', 'gender']).agg(
   total_mark=('mark', 'sum'),
   avg_mark=('mark', 'mean'),
   count=('id','count')
)
print(aggregated_data)

                    total_mark  avg_mark  count
name        gender
Alex John   male            55      55.0      1
Arnold      male            55      55.0      1
Asruid      male            85      85.0      1
Big John    female          55      55.0      1
John Deo    female          75      75.0      1
John Mike   female          60      60.0      1
Krish Star  female          60      60.0      1
Max Ruin    male            85      85.0      1
My John Rob male            78      78.0      1
Tes Qry     male            78      78.0      1

In [23]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Y.Nikithasri\Downloads\student.csv")
#df['marks_within_id'] = df.groupby('Name')['mark'].rank(ascending=False)
print(df.columns.tolist())

['id', 'name', 'class', 'mark', 'gender']

In [25]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Y.Nikithasri\Downloads\student.csv")
# Rank players within each team by Salary
df['name within mark'] = df.groupby('name')['mark'].transform(lambda x: x.rank(ascending=False))
print(df)

   id         name  class  mark  gender  name within mark
0   1     John Deo   Four    75  female               1.0
1   2     Max Ruin  Three    85    male               1.0
2   3       Arnold  Three    55    male               1.0
3   4   Krish Star   Four    60  female               1.0
4   5    John Mike   Four    60  female               1.0
5   6    Alex John   Four    55    male               1.0
6   7  My John Rob  Fifth    78    male               1.0
7   8       Asruid   Five    85    male               1.0
8   9      Tes Qry    Six    78    male               1.0
9  10     Big John   Four    55  female               1.0

In [26]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Y.Nikithasri\Downloads\student.csv")
# Filter groups where the average Salary is >= 5 million
filtered_df = df.groupby('name').filter(lambda x: x['mark'].mean() >= 1000000)
print(filtered_df)

Empty DataFrame
Columns: [id, name, class, mark, gender]
Index: []

MERGE() METHOD

In [28]:
import pandas as pd

# Create DataFrame for Dataset 1
data1 = [[1, 'Raj', 25], 
         [2, 'Sharma', 42], 
         [3, 'Saroj', 22], 
         [4, 'Raja', 51], 
         [5, 'Kajal', 26]]
df1 = pd.DataFrame(data1, columns=['ID', 'Name', 'Age'])

# Create DataFrame for Dataset 2
data2 = [[1, 'Male', 25000], 
         [2, 'Male', 42500], 
         [3, 'Female', 22300], 
         [4, 'Male', 51400], 
         [5, 'Female', 26800]]
df2 = pd.DataFrame(data2, columns=['ID', 'Gender', 'Salary'])

In [ ]:
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [30]:
merged_df = pd.merge(df1, df2, on='ID', how='left')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [31]:
merged_df = pd.merge(df1, df2, on='ID', how='right')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [32]:
merged_df = pd.merge(df1, df2, on='ID', how='outer')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [33]:
df1['Country'] = ['USA', 'Canada', 'USA', 'Canada', 'USA']
df2['Country'] = ['USA', 'Canada', 'USA', 'Canada', 'Mexico']

# Merge on 'ID' and 'Country'
merged_df = pd.merge(df1, df2, on=['ID', 'Country'], how='inner')
print(merged_df)

   ID    Name  Age Country  Gender  Salary
0   1     Raj   25     USA    Male   25000
1   2  Sharma   42  Canada    Male   42500
2   3   Saroj   22     USA  Female   22300
3   4    Raja   51  Canada    Male   51400

In [34]:
df2.rename(columns={'ID': 'EmployeeID'}, inplace=True)

# Merge using different column names
merged_df = pd.merge(df1, df2, left_on='ID', right_on='EmployeeID', how='inner')
print(merged_df)

   ID    Name  Age Country_x  EmployeeID  Gender  Salary Country_y
0   1     Raj   25       USA           1    Male   25000       USA
1   2  Sharma   42    Canada           2    Male   42500    Canada
2   3   Saroj   22       USA           3  Female   22300       USA
3   4    Raja   51    Canada           4    Male   51400    Canada
4   5   Kajal   26       USA           5  Female   26800    Mexico

PIVOT METHOD

In [35]:
import pandas as pd

# creating a dataframe
df = pd.DataFrame({'A': ['Nikitha', 'Deepu', 'Poojitha'],
                   'B': ['Masters', 'Graduate', 'Graduate'],
                   'C': [27, 23, 21]})

df

          A         B   C
0   Nikitha   Masters  27
1     Deepu  Graduate  23
2  Poojitha  Graduate  21

In [37]:
df.pivot(index='A', columns='B', values='C')

B         Graduate  Masters
A
Deepu         23.0      NaN
Nikitha        NaN     27.0
Poojitha      21.0      NaN

In [38]:
df.pivot(index='A', columns='B', values=['C', 'A'])

                C                 A
B        Graduate Masters  Graduate  Masters
A
Deepu          23     NaN     Deepu      NaN
Nikitha       NaN      27       NaN  Nikitha
Poojitha       21     NaN  Poojitha      NaN

In [41]:
import pandas as pd
df = pd.DataFrame({'A': ['Nikitha', 'Poojitha', 'Deepy'],
                   'B': ['Masters', 'Masters', 'Graduate'],
                   'C': [27, 23, 21]})


df.pivot(index='A',columns='B',values='C')

B         Graduate  Masters
A
Deepy         21.0      NaN
Nikitha        NaN     27.0
Poojitha       NaN     23.0